<?php

/**
 * Implements hook_page_attachments().
 */
function cern_loading_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'cern_loading/cernloading';
}

/**
 * Implements hook_page_top().
 */
function cern_loading_page_top(array &$page_top) {
  //$theme = \Drupal::service('theme.manager')->getActiveTheme()->getName();
  if (!isAdminPage()) {
    $page_top['cern_loading'] = [
        '#markup' => '<div id="cern-global-loading-layout"><span><span></span></span><span></span></div>',
    ];
  }
}

/**
 * Check if the current page is a admin page or edit page
 */
function isAdminPage() {
  $route = \Drupal::routeMatch()->getRouteObject();

  $is_admin = FALSE;
  if (!empty($route)) {
    $is_admin_route = \Drupal::service('router.admin_context')->isAdminRoute($route);
    $has_node_operation_option = $route->getOption('_node_operation_route');
    $is_admin = ($is_admin_route || $has_node_operation_option);
  }
  else {
    $current_path = \Drupal::service('path.current')->getPath();
    if(preg_match('/node\/(\d+)\/edit/', $current_path, $matches)) {
      $is_admin = TRUE;
    }
    elseif(preg_match('/taxonomy\/term\/(\d+)\/edit/', $current_path, $matches)) {
      $is_admin = TRUE;
    }
  }

  return $is_admin;
}