<?php
/**
 * @file
 * Install, update and uninstall functions for the easystart installation profile.
 */

/**
 * Implements hook_install_tasks().
 *
 * This is a hackish way to execute commands after the installation is fully completed. Here, for
 * incance, we can modify configuration defined in a config/install folder of a core module.
 */
function easystart_install_tasks(&$install_state) {
   $tasks = [
     'easystart_final_site_setup' => [],
   ];
   return $tasks;
}
function easystart_final_site_setup() {
  /*
   * Overwrite update.settings configuration installed from
   * /core/modules/update/config/install/update.settings.yml.
   *
   * This cannot be defined in hook_modules_installed because it raises "PreExistingConfigException
   * with message 'Configuration objects (update.settings) provided by update already exist in
   * active configuration'".
   */
  \Drupal::configFactory()->getEditable('update.settings')->set('check.interval_days', 7)->save();
  \Drupal::configFactory()->getEditable('update.settings')->set('notification.threshold', "security")->save();
}
