<?php

use Drupal\views\Plugin\views\cache\CachePluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_post_render().
 *
 * Add a CSS Class for views of type taxonomy term which will be used in menu.
 */
function cern_paragraph_menu_views_post_render(ViewExecutable $view, &$output, CachePluginBase $cache) {
  if ($view->getBaseEntityType() && $view->getBaseEntityType()->get('id') == 'taxonomy_term'){
    $view->display_handler->setOption('css_class', 'view-taxonomy-term');
  }
}