<?php

/**
 * @file
 * Contains cern_profile_displayname.module.
 */



use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cern_profile_displayname_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cern_profile_displayname module.
    case 'help.page.cern_profile_displayname':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Display real name of the user') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_profile_displayname_user_format_name_alter().
 */
 function cern_profile_displayname_simplesamlphp_auth_user_attributes(\Drupal\user\UserInterface $account, $attributes) {
  $saml_real_name = isset($attributes['fullname']) ? $attributes['fullname'] : '';
  $saml_person_id = isset($attributes['personid']) ? $attributes['personid'] : '';
  if (!empty($saml_real_name) && !empty($saml_person_id)) {
    $account->set('field_realname', $saml_real_name);
    $account->set('field_person_id_ccid', $saml_person_id);

    return $account;
  }

  return FALSE;
}

/**
 * Implements hook_user_format_name_alter().
 */
function cern_profile_displayname_user_format_name_alter(&$name, $account) {
  $member = \Drupal\user\Entity\User::load($account->id());
  if (!empty($member->field_realname->value)) {
    $config = \Drupal::config('cern_profile_displayname.settings');
    $shownameacc = $config->get('show_account_name');
    $realname = $member->field_realname->value;
    if (!$shownameacc) {
      $name = t('@realname', ['@realname' => $realname]);
    } else {
      $name = t('@realname (@username)', ['@realname' => $realname, '@username' => $member->getUsername()]);
    }
  }
}

/**
 * Helper function to return a default value if value is null.
 *
 * @param $value
 * @param $default_value
 * @return mixed
 */
function _cern_profile_displayname_get_default_value($value, $default_value) {
  if (is_null($value) || $value === '') {
    return $default_value;
  }

  return $value;
}

/**
 * Helper function to return https prefix if current connection use https.
 */
function _cern_profile_displayname_get_profiles_site_url($path) {
  if (\Drupal::request()->isSecure()) {
    return str_replace('http://', 'https://', $path);
  }
  else {
    return $path;
  }
}

/**
 * Implements hook_preprocess_hook().
 */
function cern_profile_displayname_preprocess_username (&$variables) {
  $variables['name'] = $variables['account' ]->getDisplayName();
}
