<?php
/**
 * @file
 * Install, update and uninstall functions for the cern installation profile.
 */

/**
 * Implements hook_module_preinstall().
 *
 * We want to install cern_integration before updates.
 *
 */
//function cern_module_preinstall($module) {
//  module_set_weight('cern_integration', -5);
//}

/**
 * Implements hook_modules_installed().
 */
function cern_modules_installed() {
  /*
   * Set CERN-dependent matomo configuration.
   */
  \Drupal::configFactory()
    ->getEditable('matomo.settings')
    ->set("url_http", 'http://piwik.web.cern.ch/')
    ->save();
  \Drupal::configFactory()
    ->getEditable('matomo.settings')
    ->set("url_https", 'https://piwik.web.cern.ch/')
    ->save();


    /*Set generic OIDC settings*/
  \Drupal::configFactory()
          ->getEditable("openid_connect.client.cern")
          ->set("langcode", "en")
          ->save();
  \Drupal::configFactory()
          ->getEditable("openid_connect.client.cern")
          ->set("status", "true")
          ->save();
  \Drupal::configFactory()
          ->getEditable("openid_connect.client.cern")
          ->set("id", "cern")
          ->save();
  \Drupal::configFactory()
          ->getEditable("openid_connect.client.cern")
          ->set("label", "cern")
          ->save();
  \Drupal::configFactory()
          ->getEditable("openid_connect.client.cern")
          ->set("plugin", "generic")
          ->save();

  /*Set OIDC vars*/
  $client_id= getenv('clientID');
  $client_secret= getenv('clientSecret');
  $issuer_url= getenv('issuerURL');
  \Drupal::configFactory()
          ->getEditable("openid_connect.client.cern")
          ->set("settings.client_id", $client_id)
          ->save();
  \Drupal::configFactory()
          ->getEditable("openid_connect.client.cern")
          ->set("settings.client_secret", $client_secret)
          ->save();

  /* Values set for endpoints */
  $auth_endpoint = "/protocol/openid-connect/auth";
  $token_endpoint = "/protocol/openid-connect/token";
  $userinfo_endpoint = "/protocol/openid-connect/userinfo";

  \Drupal::configFactory()
          ->getEditable("openid_connect.client.cern")
          ->set("settings.authorization_endpoint", $issuer_url.$auth_endpoint)
          ->save();
  \Drupal::configFactory()
          ->getEditable("openid_connect.client.cern")
          ->set("settings.token_endpoint", $issuer_url.$token_endpoint)
          ->save();
  \Drupal::configFactory()
          ->getEditable("openid_connect.client.cern")
          ->set("settings.userinfo_endpoint", $issuer_url.$userinfo_endpoint)
          ->save();

    /*Set custom setting to allow creation of new users*/
   \Drupal::configFactory()
          ->getEditable("user.settings")
          ->set("register", "admin_only")
          ->save();
}

/**
 * Implements hook_install_tasks().
 *
 * This is a hackish way to execute commands after the installation is fully completed. Here, for
 * incance, we can modify configuration defined in a config/install folder of a core module.
 */
function cern_install_tasks(&$install_state) {
   $tasks = [
     'cern_final_site_setup' => [],
   ];
   return $tasks;
}
function cern_final_site_setup() {
  /*
   * Overwrite update.settings configuration installed from
   * /core/modules/update/config/install/update.settings.yml.
   *
   * This cannot be defined in hook_modules_installed because it raises "PreExistingConfigException
   * with message 'Configuration objects (update.settings) provided by update already exist in
   * active configuration'".
   */
  \Drupal::configFactory()->getEditable('update.settings')->set('check.interval_days', 7)->save();
  \Drupal::configFactory()->getEditable('update.settings')->set('notification.threshold', "security")->save();
}
