<?php

/**
 * Implements hook_theme()
 *
 * Used to define the custom template of the block
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function welcome_message_block_theme($existing, $type, $theme, $path){
	return array(
			'welcome_message_block_template' => array(
				'variables' => array('site_domain' => NULL), // initialized to NULL
			),
	);
}